### ISSUE TITLE
Pictures? 

### ISSUE THREAD

**Issue by bradtn** [MapleLeafMakers/Overcasters#1]
Are there any pictures of this installed anywhere? Also whay are the preferred print settings for the diffuser etc? Thank you!

**Comment by bradtn** [comment]
Also what is the difference or use case for the different size 2020 clips? Thank you

**Comment by MapleLeafMakers** [comment]
These are still a work-in-progress, I'll add photos when they're closer to complete.  The different sized clips are to account for different extrusion profiles and tolerances, print the ones that fit your extrusions best.
